name: telegram message
on: [workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
      - name: Start SqlServer
        # You may pin to the exact commit or the version.
        # uses: 280780363/sqlserver-action@287d9e23fa7290f1a7d492ecd949291944f81c21
        uses: 280780363/sqlserver-action@v1.0
        with:
          # ACCEPT_EULA confirms your acceptance of the End-User Licensing Agreement.
          accept eula: 1
          # SA_PASSWORD - sa password, default SqlSever123123
          sa password: test123 # optional, default is SqlSever123123
